; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Thu Jul 02 2020 15:05:18 GMT+0200 (Mitteleuropäische Sommerzeit)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


