; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Thu Jul 02 2020 15:05:18 GMT+0200 (Mitteleuropäische Sommerzeit)
M280 P7 S90 I1; retract BLTouch

