; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Thu Jul 02 2020 15:05:18 GMT+0200 (Mitteleuropäische Sommerzeit)

